version: '2'
services:
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest
    
  vp1:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    extends:
      file: base/peer-secure-pbft-base.yaml
      service: peer-secure-pbft-base
    ports:
      - "8050:7050"
      - "8051:7051"
      - "8053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=${vp0}:7051
      - CORE_PEER_ID=vp1
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy

  vp2:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    extends:
      file: base/peer-secure-pbft-base.yaml
      service: peer-secure-pbft-base
    ports:
      - "9050:7050"
      - "9051:7051"
      - "9053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=${vp0}:7051
      - CORE_PEER_ID=vp2
      - CORE_SECURITY_ENROLLID=test_vp2
      - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ

  vp3:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    extends:
      file: base/peer-secure-pbft-base.yaml
      service: peer-secure-pbft-base
    ports:
      - "10050:7050"
      - "10051:7051"
      - "10053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=${vp0}:7051
      - CORE_PEER_ID=vp3
      - CORE_SECURITY_ENROLLID=test_vp3
      - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL

